### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by moha-abdi** [open-wa/wa-automate-socket-client-python#5]
I want to buy an API KEY but I wanted to test it first and it doesnt seem to be working,
I rub the code in the README.md i also scanned qr but it showed this error

```
Traceback (most recent call last):
  File "/home/moha/PycharmProjects/wapy/firsmo.py", line 5, in <module>
    client = SocketClient('http://localhost:8085/', 'secure_api_key')
  File "/home/moha/.local/lib/python3.10/site-packages/wa_automate_socket_client/__init__.py", line 43, in __init__
    self.io.connect(self.url, auth={'apiKey': api_key})
TypeError: Client.connect() got an unexpected keyword argument 'auth'
```

**Comment by smashah** [comment]
@moha-abdi you don't need to buy a license to use open wa.

License key is not the same as API key.

API Key is used to PROTECT your EASY API instance.

That is what is behind referred to in the code.

For example, if you run:

```
> npx @open-wa/wa-automate -k abcd1234
```

This will launch your EASY API with extra level of security as a header requirement for requests and websocket connections (otherwise anybody can make a request to your session and control your account).

I'm pretty sure your error is due to a wrong version of python. Please ensure you're using 3.8/3.9 before trying again.

**Comment by smashah** [comment]
This is a socketio version mismatch issue:

https://github.com/miguelgrinberg/python-socketio/issues/679#issuecomment-832202480
